Copy implementations of 4 functions from H5LTpublic.h
so we don't need to have it as a dependency. Error was:

M:\Dev\Seg3D\src\Application\LayerIO\Matlab73LayerImporter.cc(32,10): fatal error C1083: Cannot open include file: 'itkhdf5/H5LTpublic.h': No such file or directory